spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
logging:
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
server:
  port: ${PORT:8080}
  error:
    include-message: always