name: Deploy Project

on: 
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      HEROKU_KEY: ${{ secrets.HEROKU_API_KEY }}
      HEROKU_EMAIL: ${{ secrets.HEROKU_EMAIL }}
      HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: install Java
      uses: actions/setup-java@v2
      with:
        java-version: 17
        distribution: zulu

    - name: create .netrc file for heroku authentication
      run: |+
          cat >~/.netrc <<EOF
          machine api.heroku.com
              login $HEROKU_EMAIL
              password $HEROKU_KEY
          machine git.heroku.com
              login $HEROKU_EMAIL
              password $HEROKU_KEY
          EOF

    - name: login to heroku cli
      run: heroku login

    - name: add heroku as git remote
      run: heroku git:remote -a $HEROKU_APP_NAME

    - name: deploy project to heroku
      run: git push heroku HEAD:refs/heads/master
